application: picsaweb-oembed
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /(.*)\.txt
  static_files: static/\1.txt
  upload: static/(.*\.txt)

- url: /.*
  script: app.oembed

libraries:
- name: lxml
  version: latest
